# Generated by Django 4.0.3 on 2022-03-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(verbose_name='Цитата')),
                ('num_letters', models.IntegerField(verbose_name='Общее количество букв')),
                ('num_vowels', models.IntegerField(verbose_name='Количество гласных букв')),
                ('num_consonants', models.IntegerField(verbose_name='Количество согласных букв')),
                ('average', models.IntegerField(verbose_name='Средняя длина всех слов в цитате')),
                ('long_word_1', models.CharField(max_length=255, verbose_name='Длинное слово 1')),
                ('long_word_2', models.CharField(max_length=255, verbose_name='Длинное слово 2')),
                ('long_word_3', models.CharField(max_length=255, verbose_name='Длинное слово 3')),
            ],
        ),
    ]
