# Generated by Django 4.0.3 on 2022-03-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_alter_quote_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='num_repetition',
            field=models.TextField(default='default', verbose_name='Общее количество повторений каждой буквы'),
            preserve_default=False,
        ),
    ]
